name: Caller Workflow
run-name: Triggered by @${{ github.actor }}

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable.yaml
    with:
      username: 'james enoh and MTE'
