name: Reusable Workflow
run-name: print_username


on:
  workflow_dispatch: 
    inputs:
        username:
          description: 'A username passed from the caller workflow'
          default: 'john-doe'
          required: false
          type: string
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}
      - name: PowerShell Step
        run: |
          ./caller_workflow/scripts/hello-world.ps1
